name: Create Temporary Branch and mergenew1234
 
on:
  push:
    branches:
      - develp
 
jobs:
  create_temp_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
          repository: cloudtrio/automation
          token: ${{ secrets.GIT }}
          ref: develop
 
    - name: Create temporary branch for develop
      run: |
        git checkout -b temp/develop
        git push origin temp/develop
 
    - name: Checkout staging branche
      uses: actions/checkout@v4
      with: 
          repository: cloudtrio/automation
          token: ${{ secrets.GIT }}
          ref: staging
    - name: Create temporary branch for staging
      run: | 
        git checkout -b temp/staging
        git push origin temp/staging
    - name: Create Pull Request for merging temp/develop into staging
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.GIT }}
          commit-message: "Merge temp/develop into staging"
          title: "Merge temp/develop into staging"
          body: |
            This pull request merges changes from temp/develop into the staging branch.
          branch: staging
          base: develop

        

